# Default values for node.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  name: xwiki
  pullPolicy: IfNotPresent
  tag: lts-mysql-tomcat
service:
  portName: node
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 350m
    memory: 1000Mi
  requests:
    cpu: 150m
    memory: 250Mi
mysql:
  mysqlRootPassword: xwiki
  mysqlUser: xwiki
  mysqlPassword: xwiki
  mysqlDatabase: xwiki
  imageTag: 5.7
env:
  - name: 'DB_USER'
    value: 'xwiki'
  - name: 'DB_PASSWORD'
    value: 'xwiki'
  - name: 'DB_HOST'
    value: 'xwiki-mysql'
  - name: 'DB_DATABASE'
    value: 'xwiki'
ingress:
  enabled: true
  issuer: dev-issuer
  annotations:
    kubernetes.io/ingress.class: nginx
storage: "1Gi"
storageClassName: "my-storage-class"
buildID: "123"
